# Generated by Django 5.1.5 on 2025-02-02 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('followers', models.IntegerField()),
                ('topics', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('verification_status', models.CharField(choices=[('Verified', 'Verified'), ('Debunked', 'Debunked'), ('Questionable', 'Questionable')], max_length=50)),
                ('trust_score', models.IntegerField(default=0)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verifyinfluencers.influencer')),
            ],
        ),
    ]
