# Generated by Django 5.1.5 on 2025-02-03 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifyinfluencers', '0002_remove_influencer_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthclaim',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthclaims', to='verifyinfluencers.influencer'),
        ),
    ]
